### PR TITLE
Update create_jira_issue.html

### PR DESCRIPTION
**Pull request by dannygeek**
Support Sentry 8.0.0

### CODE REVIEW

**Comment by dcramer** [comment]
fwiw we likely have a bunch of changes in https://github.com/getsentry/sentry-jira

It might be worth just merging the repos at this point

**Comment by gregwjacobs** [comment]
+1

**Comment by thurloat** [comment]
@dcramer I'm on board with this plan. Let me know how you'd like to manage that.

**Comment by dcramer** [comment]
@thurloat i will make sure both repos are merged up, then we can probably kill this repo and move yours over. Will ping this thread when ready.

**Comment by dcramer** [comment]
Repo is merged up

**Pull request closed without merging**
