### PR TITLE
Provide support for default priority and default issue type when creating JIRA tickets.

### PR DESCRIPTION
**Pull request by rogerhu**
Also expose an auto-create button for filing JIRA tickets.

One known limitation: you must update the project name to update the default issue type if they are different across different projects.  I tried a bunch of different JS approaches to do it, but figured the easier thing for now is just to require 2 saves.

image

### CODE REVIEW

**Comment by rogerhu** [comment]
The Sentry plugin is currently broken on newer versions... see https://github.com/hearsaycorp/sentry-jira/commit/c91b5fd4edf17369537bdb17ed6fb958ba01bb9c (and the commit that broke stuff https://github.com/getsentry/sentry/commit/68a30d95644295af1aa077aa6d04c183309b5743)

**Comment by dcramer** [comment]
@rogerhu the released version is broken but HEAD of thurloat/sentry-jira is ok (we're syncing most changes between getsentry and this repo atm)

**Comment by dcramer** [comment]
The auto create stuff we actually plan to move elsewhere in the future, but since we haven't done it yet I'm fine with accepting it here.

**Comment by dcramer** [comment]
I merged most of this in, but we're actually going to remove auto creation until Sentry supports it as a native concept.

**Pull request closed without merging**
